### ISSUE TITLE
[BUG] The yarn.lock is out of sync with package.json since the 0.2.0 commit

### ISSUE THREAD

**Issue by ksquaredkey** [hoptical/grafana-kafka-datasource#35]
**Describe the bug**
I'm pretty ignorant of Node/npm/yarn, but "yarn install" has been failing and I believe it is because the committed "yarn.lock" file is from the v0.1.0 commit and was not updated with the v0.2.0 commit of the new "package.json".  When I blew away the yarn.lock and let it regenerate, I was finally able to complete "yarn install"

**To Reproduce**
1. Create new clean dev environment: Ubuntu 2022.04; node v16.16.0 LTS (npm 8.11.0); yarn 1.22.19 ; go 1.18.1)
2. git clone and cd into grafana-kafka-datasource/
3. Type: yarn install
4. The install blows up while building "node-sass"

**Expected behavior**
For "yarn install" to succeed.

**Screenshots**
Fails with below.  Full result attached to ticket
[grafana-kafka-datasource-errors.txt](https://github.com/hoptical/grafana-kafka-datasource/files/9247068/grafana-kafka-datasource-errors.txt)
`
mpatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  847 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/key/.node-gyp/16.16.0/include/node/node.h:881:3: note: in expansion of macro ‘NODE_MODULE_X’
  881 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’
  358 | NODE_MODULE(binding, RegisterModule);
      | ^~~~~~~~~~~
make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/key/Grafana-builds/grafana-kafka-datasource/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/key/Grafana-builds/grafana-kafka-datasource/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.0-43-generic
gyp ERR! command "/home/key/.nvm/versions/node/v16.16.0/bin/node" "/home/key/Grafana-builds/grafana-kafka-datasource/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/key/Grafana-builds/grafana-kafka-datasource/node_modules/node-sass
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v3.8.0
`

**Desktop Information:**
 - OS: Ubuntu 2022.04
 - Browser: N/A
 - Plugin Version:0.2.0
 - Grafana Version: 8.5.5 - but didn't get that far

**Additional context**
When I finally thought of deleting the yarn.lock, the "yarn install" succeeded.  I am looking at adding TLS and auth configuration (issue #20), but I need a known good working dev environment before I can dive into the Go side of things.

**Comment by ksquaredkey** [comment]
I confirmed my basic build environment by rebuilding the git@github.com:michelin/snowflake-grafana-datasource.git successfully, so I think it is local to this project.

**Comment by ksquaredkey** [comment]
I just tied to build with v0.1.0 tag and it blew up the same way, so maybe not the yarn.lock version.  I'm open to suggestions for dev environment.

**Comment by ksquaredkey** [comment]
However, removing the yarn.lock file did allow me to build v0.1.0 successfully.  When I try with v0.2.0. (nuking yarn.lock), the yarn build fails with:
`key@grafana-build:~/Grafana-builds/grafana-kafka-datasource-upstream$ yarn build
yarn run v1.22.19
warning ../../package.json: No license field
$ grafana-toolkit plugin:build
  Using Node.js v16.16.0
  Using @grafana/toolkit v9.0.6
✔ Preparing
✔ Linting
No tests found, exiting with code 0
✔ Running tests
⠇ Compiling...  TS2322: Type '{ css: true; checked: boolean; onChange: (event: SyntheticEvent<HTMLInputElement, Event>) => void; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, "key" | "cite" | "data" | "form" | "label" | "slot" | "span" | "style" | "summary" | "title" | "pattern" | "children" | ... 348 more ... | "transparent"> & RefAttributes<...>'.
    Property 'css' does not exist on type 'IntrinsicAttributes & Pick<Props, "key" | "cite" | "data" | "form" | "label" | "slot" | "span" | "style" | "summary" | "title" | "pattern" | "children" | ... 348 more ... | "transparent"> & RefAttributes<...>'.
      107 |             </InlineFormLabel>
      108 |             <div className="add-data-source-item-badge">
    > 109 |               <Switch css checked={withStreaming || false} onChange={this.onWithStreamingChange} />
          |                       ^^^
      110 |             </div>
      111 |           </InlineFieldRow>
      112 |         </div>
✖ Build failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
key@grafana-build:~/Grafana-builds/grafana-kafka-datasource-upstream$`

**Comment by hoptical** [comment]
@ksquaredkey Thanks for reaching out and your willingness to contribute.  
I'd make a guess that is because of your node version. I've cloned the repo and performed `yarn install` with the below config, and the installation proceeded successfully.
- Ubuntu 20.04 LTS
- **node v14.19.3  (npm 6.14.17)**
- yarn 1.22.19
- go 1.18

So please try with _Node v14_ and _npm v6_ and let me know if it works or not.

**Comment by ksquaredkey** [comment]
Success! With Node v14 - I used v14.20.0 - lts/fermium installed via "nvm".  

The "yarn install" and "yarn build" worked but still threw a bunch of warnings.  What version of grafana-toolkit are you using?  I see the grafana devDependencies are all set to "latest".  I received:

$ grep version */package.json
data/package.json:  "version": "7.3.7",
e2e-selectors/package.json:  "version": "7.3.7",
eslint-config/package.json:  "version": "2.0.3",
runtime/package.json:  "version": "7.3.7",
slate-react/package.json:  "version": "0.22.9-grafana",
toolkit/package.json:  "version": "7.3.7",
tsconfig/package.json:  "version": "1.0.0-rc1",
ui/package.json:  "version": "7.3.7",

The warnings I see are:
$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "rxjs@7.3.0" is incompatible with requested version "rxjs@6.6.2"
warning Resolution field "rxjs@7.3.0" is incompatible with requested version "rxjs@^6.4.0"
warning Resolution field "rxjs@7.3.0" is incompatible with requested version "rxjs@^6.3.3"
warning Resolution field "rxjs@7.3.0" is incompatible with requested version "rxjs@^6.4.0"
warning Resolution field "rxjs@7.3.0" is incompatible with requested version "rxjs@^6.5.3"
warning Resolution field "rxjs@7.3.0" is incompatible with requested version "rxjs@6.6.3"
[3/5] Fetching packages...
warning Pattern ["@grafana/ui@latest"] is trying to unpack in the same destination "/home/key/.cache/yarn/v6/npm-@grafana-ui-7.3.7-c87a4af6a1357db9cd46fee680065ece5a175bf3-integrity/node_modules/@grafana/ui" as pattern ["@grafana/ui@7.3.7"]. This could result in non-deterministic behavior, skipping.
[4/5] Linking dependencies...
warning "@grafana/toolkit > ts-jest@26.3.0" has incorrect peer dependency "jest@>=26 <27".
warning "@grafana/toolkit > @grafana/ui > @grafana/slate-react > slate-react-placeholder@0.2.9" has unmet peer dependency "slate-react@>=0.22.0".
warning "@grafana/toolkit > @grafana/ui > @torkelo/react-select > react-input-autosize@2.2.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning "@grafana/toolkit > @grafana/ui > rc-cascader > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react@^16.0.0".
warning "@grafana/toolkit > @grafana/ui > rc-cascader > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react-dom@^16.0.0".
[5/5] Building fresh packages...
Done in 19.14s.

I don't know if those are "normal" in the Node world.

For completeness, I am using:
* Ubuntu 22.04 LTS
* node v14.20.0 (npm 6.14.17)
* yarn 1.22.19
* go 1.18.1

**Comment by hoptical** [comment]
Great! About the warnings, they're completely fine, and I have them too. So I can say that you're ready to go.
In terms of the grafana-toolkit, my version is v9.0.6.

**Comment by ksquaredkey** [comment]
I successfully got the plugin demo working - thanks for the help!

**Comment by hoptical** [comment]
You're welcome. Glad to hear it!
